### PR TITLE
Generate PEAN stack app structure with Yeoman

### PR DESCRIPTION
**Pull request by amyyli**
Used this generator for AngularJS + Express + PostgreSQL: https://www.npmjs.com/package/generator-angular-express.

Added .gitignore file.

Take a look and see if this is the structure that we want. :smiley:

### CODE REVIEW

**Comment by amyyli** [comment]
This also comes with Grunt. Maybe gulp is better?

**Comment by recursion** [comment]
I think either grunt or gulp could be good starting choices, so long as they do what we need.     I have noticed some repos that include both, so I think whichever does what we need first is a good criteria there :P

Seems like a good concept - generators are a great way to keep the structure consistent, so Im all for it! Have not had a chance to dig through this one yet however, and will do so and comment further asap.

**Comment by recursion** [comment]
I can imagine the directory structure looking something more like this eventually:

screen shot 2015-07-11 at 9 36 04 pm

**Comment by mnaamani** [comment]
I noticed in their README this:
> Automatic creation of PostgreSQL database and user
Knex configured for use with knex migrate and knex seed
... working on adding Bookshelf.js ...

does it mean it we cannot work with Bookshelf ?

**Comment by recursion** [comment]
I believe it just means we will have to wire it up ourselves.

**Comment by mnaamani** [comment]
It is also missing a few generators that normally a yoeman generator provides, for creating new controllers, services, etc.. or am I missing something?

`yo new controller MyController`
`yo new service MyService`

that sort command.

**Comment by recursion** [comment]
No you are absolutely correct. It does not appear to do anything but generate the initial application skeleton. Which I actually really like. To me, they framed it right out to where we can make the next directory structure decisions. (And they even like to the front-end/angular style guide)

**Comment by recursion** [comment]
Here is something that has way more to configure - and its hard to say how much extra fat is has on it... but it has some generators:
https://www.npmjs.com/package/generator-soa

**Comment by mnaamani** [comment]
I wonder can we use it in combination with https://www.npmjs.com/package/generator-angular

**Comment by recursion** [comment]
Yeah that seems like it would work really well together!

**Comment by recursion** [comment]
This looks promising?
https://www.npmjs.com/package/generator-sql-fullstack

**Comment by simonburns77** [comment]
"Only those with write access to this repository can merge pull requests.", can I get bumped to write access please :)

**Comment by amyyli** [comment]
@simonburns77 I believe you got an email a while back inviting you to the GitHub org, something like:

"[GitHub] Richard Treichel has invited you to join the FlipSideHR organization"

**Pull request merged**
