### PR TITLE
reverted to old model setup

### PR DESCRIPTION
**Pull request by mnaamani**
- Reverted to old way of loading models, to fix issue with relations.
- Updated tests.
- All server unit tests passing.
- Ready to merge.

### CODE REVIEW

**Comment by recursion** [comment]
Woot! 
Nice job!
Ill take one more look at this once I have coffee and then merge!

**Comment by mnaamani** [comment]
@recursion  So I pushed one more commit to use the bookshelf model registery which you suggested 

https://github.com/tgriesser/bookshelf/wiki/Plugin:-Model-Registry

and added one unit test to for checking all the model relations, and finally it is working..

**Comment by mnaamani** [comment]
screen shot 2015-07-18 at 11 42 06 am

**Comment by recursion** [comment]
Awesome!

**Pull request merged**
