### PR TITLE
Scrap TechanJS and restructure AngularJS client

### PR DESCRIPTION
**Pull request by amyyli**
We scrapped TechanJS due to lack of good documentation. Shelved the files in client/components/chart/techan/.

Restructured front-end with a proper Angular file structure following this guideline: https://scotch.io/tutorials/angularjs-best-practices-directory-structure.

Working on fixing the Gruntfile after file restructuring. Grunt aborts at karma:unit. :scream_cat:

### CODE REVIEW

**Comment by recursion** [comment]
Ill just leave this here:
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/

**Comment by mnaamani** [comment]
The problem is that the grunt task is configured to only run once....

in Gruntfile.js:

    karma: {
          unit: {
            configFile: 'test/karma.conf.js',
            autoWatch: false,
            singleRun: true,   // <<------- source of the problem
            browsers: ['PhantomJS']
          }
        },

Use this configuration and 

    karma: {
          unit: {
            configFile: 'test/karma.conf.js',
            autoWatch: true,
            singleRun: false,
            browsers: ['PhantomJS']
          }
        },

grunt will not exit.. and karma will keep running watching files and re running the unit tests on file change.

**Comment by mnaamani** [comment]
And I added a .bowerrc in https://github.com/FlipSideHR/FlyptoX/pull/27 so components will be installed to correct directory

**Comment by amyyli** [comment]
@mnaamani So clutch! :+1:

**Comment by recursion** [comment]
Looks good!

**Pull request merged**
