### PR TITLE
Implemented basic tests for user, object and trade models.

### PR DESCRIPTION
**Pull request by recursion**
**RequestForComment:**

- made some slight adjustments to the server mocha test structure - it now looks for tests in 'test/server/***/**.spec.js', and as such I have moved model tests into test/server/models/
- Im curious about some of the knex tables not using 'notNullable()' on primary key? Have we actually established that these do or do not need to be used on certain keys? Or?
- This PR introduces a variation on the way bookshelf gets loaded and passed around: 
     - one module does the bookshelf config, and exports that. 
     - just require it anywhere you need that config, and bam, you got yourself a bookshelf.
- neither the tests nor the models are doing too much yet, but the groundwork has been laid, and I am inching forward here.
- the current tests are setup to remove(from db) any entries made to the db during testing as long as you follow the existing pattern of pushing new entries onto the `test_<model>` array (see more in comments)
- I am inching towards testing something with relationships (trades in this case) - which requires some building out of other models first - once I can start verifying that that works as expected, things should start progressing a bit faster? :)

**Known issues**
- Some tests will fail on the first run (being addressed)
- Must create an entry in the db:
     - `insert into currency_pairs values(1, 'XBT/USD');`

### CODE REVIEW

**Comment by RWTreichel** [comment]
**Regarding .primary() and .notNullable():**
I went hunting for this for a while the other day, and ended up digging into source code. [Here](https://github.com/tgriesser/knex/blob/5e65678b32fa639843902d39603ab2050d84f10f/src/dialects/postgres/schema/tablecompiler.js) is the file that defines what .primary() does in Knex for a Postgres database.
The relevant line is:
```
TableCompiler_PG.prototype.primary = function(columns) {
  this.pushQuery('alter table ' + this.tableName() + " add primary key (" + this.formatter.columnize(columns) + ")");
};
```
Based on that, I went to check out how Postgres would handle that command. Check out "5.3.4. Primary Keys" [here](http://www.postgresql.org/docs/8.1/static/ddl-constraints.html). According to that, denoting a column as a primary key is almost like a shortcut which really says "unique and not null" (although it does add one other constraint, namely, a table can only have one primary key, although it can have other columns that are unique and not null).

**Comment by RWTreichel** [comment]
On that note, I don't think applying .notNullable() is harmful. Redundant, maybe, but that might be the way to go just to be sure.

**Comment by recursion** [comment]
Closing this while i resolve further merge issues.

**Comment by mnaamani** [comment]
can we create a seed file to populate  the currency and currency pairs tables?

**Comment by recursion** [comment]
Yeah we need to, I just haven't gotten around to it!

**Comment by mnaamani** [comment]
I think this is very well structured, and good step forward.
LGTM ok to merge

**Comment by mnaamani** [comment]
Actually can we discuss the matter of how bookshelf is passed around?
I think when it comes to passing around another similar object.. such as the 'app event' object
we might want to pass it around in the same way..
so it makes sense to place it on the app and retrieve it with app.get('AppEvents')

**Comment by recursion** [comment]
The apps bookshelf is currently attached to app with app.set('bookshelf', bookshelf) which is fine for accessing bookshelf I guess from within other parts of the express app.

However in the case of the models, it didnt really make sense for them to have access to the entire app just to get bookshelf,  especially when it comes to testing those modules.

**Comment by mnaamani** [comment]
good point, lets go with this approach it makes a lot more sense.
merging

**Pull request merged**
